/**
 * Main entrypoint into VividCortex entity functionality.
 *
 * @file This files defines the core nr1-vividcortex nerdlet class.
 * @author Gil Rice
 */
/** core */
import React from 'react';
/** nr1 */
import { PlatformStateContext } from 'nr1'
import { NerdletStateContext } from 'nr1';
/** local */
import VCEntity from '../vcpoc';
/** 3rd party */

/**
 * Code class generated by New Relic One CLI.
 */
export default class Nr1Vividcortex extends React.Component {
    render() {
        return (
            <PlatformStateContext.Consumer>
              {launcherUrlState => (
                <NerdletStateContext.Consumer>
                  {nerdletUrlState => (
                    <VividCortexHostNerdlet
                      launcherUrlState={launcherUrlState}
                      nerdletUrlState={nerdletUrlState}
                      nerdlet_timerange={launcherUrlState.timeRange}
                    />
                  )}
                </NerdletStateContext.Consumer>
              )}
            </PlatformStateContext.Consumer>
          );
    } //render
} //Nr1Vividcortex